---

dependencies:
  - 'debops.nginx'

galaxy_info:

  company: 'DebOps'
  author: 'Norbert Summer'
  description: 'feature rich metrics dashboard and graph editor'
  license: 'GPL-3.0'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Debian
      versions:
        - stretch

    - name: Ubuntu
      versions:
        - xenial
        - artful

  galaxy_tags:
    - grafana
    - monitor
