---

- name: 'Install prometheus exporter packages'
  apt:
    pkg: '{{ item }}'
    state: 'present'
    install_recommends: 'no'
  with_flattened:
    - '{{ prometheus_exporters__base_packages }}'
    - '{{ prometheus_exporters__packages }}'

- name: 'build postfix'
  include: 'build_postfix.yml'
  when: ('postfix' in prometheus_exporters__exporters)

- name: 'Start Services'
  service:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'started'
  with_flattened:
    - "{{ ['prometheus-node-exporter'] if 'node' in prometheus_exporters__exporters else [] }}"
    - "{{ ['prometheus-mysqld-exporter'] if 'mysqld' in prometheus_exporters__exporters else []  }}"
    - "{{ ['prometheus-postfix-exporter'] if 'postfix' in prometheus_exporters__exporters else []  }}"
