---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.prometheus_exporters default variables [[[
# =============================================

# .. contents:: Sections
#    :local:

# Packages and installation [[[
# -------------------------

# .. envvar:: prometheus_exporters__base_packages [[[
#
# List of base packages to install.
prometheus_exporters__base_packages:
  "{{ 'prometheus-node-exporter'     if 'node' in prometheus_exporters__exporters else []
    + 'prometheus-mysqld-exporter'   if 'mysqld' in prometheus_exporters__exporters else []
    + [ 'golang', 'libsystemd-dev' ] if 'postfix' in prometheus_exporters__exporters else [] }}"
                                                                   # ]]]
                                                                   # ]]]
# .. envvar:: prometheus_exporters__packages [[[
#
# List of additional APT packages to install with prometheus.
prometheus_exporters__packages: []
                                                                   # ]]]
                                                                   # ]]]
# prometheus exporter Configuration [[[
# ---------------------------------

# .. envvar:: prometheus_exporters__deploy_state [[[
#
# Set to `absent` to disable and uninstall this role
prometheus_exporters__deploy_state: "present"
                                                                   # ]]]
# .. envvar:: prometheus_exporters__exporters [[[
#
prometheus_exporters__exporters:
  - 'node'
#  - 'mysqld'
#  - 'postfix'
                                                                   # ]]]
# .. envvar:: prometheus_exporter__mysql__dependencies [[[
#
# mysql connection for monitoring
prometheus_exporter__mysql__dependencies:
  - user: 'prometheus'
    owner: 'prometheus'
    group: 'prometheus'
    home: '/var/lib/prometheus'
    system: True
    priv_aux: False
    priv_default: False
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
                                                                   # ]]]
                                                                   # ]]]
# Ngninx Proxy [[[
# ------------
#
# This is soposed to secure the access to the prometheus exporter

# .. envvar:: prometheus_exporters__public [[[
#
# Enables an nginx proxy for the prometheus exporter
prometheus_exporters__nginx: False
                                                                   # ]]]
# .. envvar:: prometheus_exporters__domain [[[
#
# Domain to use for vserver on nginx proxy
prometheus_exporters__domain: 'metric.{{ ansible_fqdn }}'
                                                                   # ]]]
# .. envvar:: prometheus_exporters__nginx__dependent_servers [[[
#
# Domain to use for vserver on nginx proxy
prometheus_exporters__nginx__dependent_servers:
  - enabled: '{{ prometheus_exporters__nginx }}'
    name: [ '{{ prometheus_exporters__domain }}' ]
    type: 'proxy'
    location:
      '/exporter/node': |
         rewrite /exporter/node/(.*) /$1 break;
         proxy_pass http://localhost:9100;
      '/exporter/mysqld': |
         rewrite /exporter/mysqld/(.*) /$1 break;
         proxy_pass http://localhost:9104;
      '/exporter/postfix': |
         rewrite /exporter/postfix/(.*) /$1 break;
         proxy_pass http://localhost:9154;
    auth_basic: True
    auth_basic_name: 'prometheus_exporters'
                                                                   # ]]]
                                                                   # ]]]
# Role-dependent configuration [[[
# ----------------------------

# .. envvar:: prometheus_exporters__accept_any [[[
#
# Make the prometheus exporter aviable under the port 9090
prometheus_exporters__accept_any: False
                                                                   # ]]]
# .. envvar:: prometheus_exporters__allow [[[
#
# List of IP addresses or CIDR subnets which can access the prometheus exporter
# By default access is from the net is forbidden
prometheus_exporters__allow: []
                                                                   # ]]]
# .. envvar:: prometheus_exporters__ferm__dependent_rules [[[
#
# Ferm rules
prometheus_exporters__ferm__dependent_rules:
  - name: 'prometheus_exporter_node'
    type: 'accept'
    dport: '9100'
    accept_any: '{{ prometheus_exporters__accept_any }}'
    by_role: 'prometheus_exporters'
    rule_state: '{{ prometheus_exporters__deploy_state if "node" in prometheus_exporters__exporters else "absent" }}'
  - name: 'prometheus_exporter_mysqld'
    type: 'accept'
    dport: '9104'
    accept_any: '{{ prometheus_exporters__accept_any }}'
    by_role: 'prometheus_exporters'
    rule_state: '{{ prometheus_exporters__deploy_state if "node" in prometheus_exporters__exporters else "absent" }}'
  - name: 'prometheus_exporter_postfix'
    type: 'accept'
    dport: '9154'
    accept_any: '{{ prometheus_exporters__accept_any }}'
    by_role: 'prometheus_exporters'
    rule_state: '{{ prometheus_exporters__deploy_state if "node" in prometheus_exporters__exporters else "absent" }}'
                                                                   # ]]]
# .. envvar:: prometheus_exporters__tcpwrappers__dependent_allow [[[
#
# Configuration for the debops.tcpwrappers Ansible role.
prometheus_exporters__tcpwrappers__dependent_allow:
  - daemon: '{{ [ "prometheus-node-exporter" ] if "node" in prometheus_exporters__exporters else []
          + [ "prometheus-mysqld-exporter" ] if "mysqld" in prometheus_exporters__exporters else []
          + [ "prometheus-postfix-exporter" ] if "postfix" in prometheus_exporters__exporters else [] }}'
    client: '{{ prometheus_exporters__allow }}'
    accept_any: '{{ prometheus_exporters__accept_any }}'
    filename: 'prometheus-exporters'
                                                                   # ]]]
# .. envvar:: prometheus_exporters__etc_services__dependent_list [[[
#
# Configuration for :ref:`debops.etc_services` role. It will set up
# a entry in :file:`/etc/services`.
prometheus_exporters__etc_services__dependent_list:
  - name: 'prometheus_node_exporter'
    port: 9100
    comment: 'Prometheus node exporter for metric providing'
  - name: 'prometheus_mysqld_exporter'
    port: 9104
    comment: 'Prometheus mysql exporter for metric providing'
  - name: 'prometheus_postfix_exporter'
    port: 9154
    comment: 'Prometheus postfix exporter for metric providing'
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
