---


- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ prometheus_alertmanager__base_packages }}'
    - '{{ prometheus_alertmanager__packages }}'

- name: Enable Services
  service:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'started'
  with_items:
    - prometheus-alertmanager
