---


- name: Install required packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ prometheus_alertmanager__base_packages }}'
    - '{{ prometheus_alertmanager__packages }}'

- name: Copy Configuration
  template:
    dest: "/etc/prometheus/alertmanager.yml"
    src: "etc/prometheus/alertmanager.yml.j2"

- name: Enable Services
  service:
    name: '{{ item }}'
    enabled: 'yes'
    state: 'started'
  with_items:
    - prometheus-alertmanager
