---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.prometheus_server default variables [[[
# ====================================

# .. contents:: Sections
#    :local:

# Packages and installation [[[
# -----------------------------

# .. envvar:: prometheus_server__base_packages [[[
#
# List of base packages to install.
prometheus_server__base_packages:
  - prometheus
                                                                   # ]]]
# .. envvar:: prometheus_server__packages [[[
#
# List of additional APT packages to install with prometheus.
prometheus_server__packages: []
                                                                   # ]]]
# .. envvar:: prometheus_server__apt_preferences__dependent_list [[[
#
# List of apt_preference settings to use backports on stretch
prometheus_server__apt_preferences__dependent_list:
  - packages:
      - prometheus
    backports: [ 'stretch' ]
    reason: 'Stable version has some ram leaking problems'
    by_role: 'debops.prometheus_server'
                                                                   # ]]]
                                                                   # ]]]
# Prometheus Server Configuration [[[
# --------------------------

# .. envvar:: prometheus_server__deploy_state [[[
#
# Set to `absent` to disable and uninstall this role
prometheus_server__deploy_state: "present"
                                                                   # ]]]
# .. envvar:: prometheus_server__default_scrape_configs [[[
#
# Default prometheus config
#
# Creates for each entry a file that will get loaded by
# TODO better varable description
prometheus_server__default_scrape_configs:
  default:
    - labels:
        job: 'prometheus'
        env: 'prod'
      targets: ['localhost:9090']
    - labels:
        job: 'node'
        env: 'prod'
      targets: [ 'localhost:9100' ]
                                                                   # ]]]
# .. envvar:: prometheus_server__scrape_configs [[[
#
# Config which will be managed on all hosts in the Ansible
# inventory
prometheus_server__scrape_configs: []
                                                                   # ]]]
# .. envvar:: prometheus_server__group_scrape_configs [[[
#
# Config which will be managed on specific groups in the Ansible
# inventory.
prometheus_server__group_scrape_configs: []
                                                                   # ]]]
# .. envvar:: prometheus_server__host_scrape_configs [[[
#
# Config which will be managed on specific hosts in the Ansible
# inventory.
prometheus_server__host_scrape_configs: []
                                                                   # ]]]
# .. envvar:: prometheus_server__combined_scrape_configs [[[
#
# List which combines all of the config variables and is used
# in the configuration template.
prometheus_server__combined_scrape_configs: '{{ prometheus_server__default_scrape_configs
                                       + prometheus_server__scrape_configs
                                       + prometheus_server__group_scrape_configs
                                       + prometheus_server__host_scrape_configs  }}'
                                                                   # ]]]
                                                                   # ]]]
