---


- hosts: [ 'debops_service_prometheus_server' ]
  roles:
    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'role::prometheus' ]
      apt_preferences__dependent_list:
        - '{{ prometheus_server__apt_preferences__dependent_list }}'
    - role: debops.ferm
      tags: [ 'role::ferm', 'role::nginx' ]
      ferm__dependent_rules:
        - '{{ prometheus_server__ferm__dependent_rules }}'
    - role: debops.prometheus_server
      tags: [ 'role::prometheus' ]

