---

- hosts: [ 'debops_service_prometheus_exporters' ]
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  roles:
    - role: debops.prometheus_exporters
      tags: [ 'role::prometheus_exporters' ]
    - role: debops.mariadb
      tags: [ 'role::mariadb', 'role::prometheus_exporters' ]
      mariadb__dependent_users: '{{ prometheus_exporters__mysql_dependencies }}'
      when: ('mysql' in prometheus_exporters__exporters)
