---


grafana__deploy_state: "present"

grafana__apt__repositories:
  - repo: 'deb https://packagecloud.io/grafana/stable/debian/ {{ ansible_distribution_release }} main'
    filename: 'grafana'

grafana__apt__keys:
  - url: 'https://packagecloud.io/gpg.key'

grafana__base_packages:
  - grafana

grafana__packages: []

grafana__public: True

grafana__nginx__dependent_servers:
  - enabled: '{{ grafana__public }}'
    name: [ 'monitor.{{ ansible_domain }}' ]
    type: 'proxy'
    proxy_pass: 'http://localhost:3000/'
